# TODO osx
os: linux
dist: trusty
sudo: required
language: generic
addons:
  apt:
    update: true

before_script:
  # install conda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  # update conda
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install -c conda-forge conda-build conda-verify
  - conda info -a
  # install additional dependencies for tests
  # - conda install -c conda-forge zarr h5py

script:
  - conda build -c conda-forge conda-recipe
