package:
  name:
    z5py
  {% set tagged_version = GIT_DESCRIBE_TAG|replace("v","")|replace("-", ".") %}
  {% if GIT_DESCRIBE_NUMBER|int != 0 %}
    {% set tagged_version = tagged_version + '.post' + GIT_DESCRIBE_NUMBER %}
  {% endif %}
  version:
   {{tagged_version}}


source:
  path: ..


build:
  number: 0
  string: py{{python}}_{{PKG_BUILDNUM}}_g{{GIT_FULL_HASH[:7]}}


requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python {{python}}*
    - boost-cpp {{ boost }}
    - xtensor {{ xtensor }}
    - xtensor-python {{ xtensor_python }}
    - numpy {{ numpy }}
    - nlohmann_json
    - blosc
    - bzip2
    - xz
    - zlib
  run:
    - {{ pin_compatible('python', max_pin='x.x') }}
    - {{ pin_compatible('boost-cpp', max_pin='x.x.x') }}
    - {{ pin_compatible('numpy', min_pin='x.x') }}
    - six
    - blosc
    - bzip2
    - xz
    - zlib
    - futures  # [py2k]


test:
  imports:
    - z5py
  requires:
    - pytest
    - h5py
  source_files:
    - src/python/test/*
  commands:
    - pytest src/python/test
